# Generated by Django 5.0.6 on 2024-06-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'No disponible'), ('p', 'En prestamo'), ('d', 'Disponible'), ('r', 'Reservado')], default='d', help_text='Disponibilidad del libro', max_length=1),
        ),
    ]
