# Generated by Django 5.0.6 on 2024-06-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('marcar_libro', 'Marcar una libro regresado'))},
        ),
    ]
